######################
#	升级配制文件     #
#   (20210113)       #
######################
#项目名
PROJECT=SX11RA
#车型版本（1：PERSONA 2：IRIZ）
PLATFORM=1
#当前要升级的版本，如果为1，表示不指定升级版本，方可降低升级。
MCU_VERSION=AEJ
MPU_VERSION=SWE22HR0807H0AEJ.00785
VR_VERSION=cerence_24.03.13
#如果为MD5为-1不做MD5校验
MCU_MD5=-1
MPU_MD5=-1
#默认SEQ(状态值0：MCU->MPU-VR,1:MPU->MCU-VR)升级顺序
SEQ=1
#版本号唯一标识
VERSION_CODE=00785
